<?php namespace common\components\base;

use Yii;
use yii\base\ActionFilter;
use yii\web\BadRequestHttpException;


class AjaxFilter extends ActionFilter
{
    public $actions = [];

    public function beforeAction($action)
    {
        if (in_array($action->id, $this->actions)) {
            if (!Yii::$app->request->isAjax) {
                throw new BadRequestHttpException;
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}