<?php namespace common\components\base;

class Security extends \yii\base\Security
{
    public function encryptByPassword($data, $password = '')
    {
        $password = $password ?: \Yii::$app->params['cipherPassword'];
        return parent::encryptByPassword($data, $password); // TODO: Change the autogenerated stub
    }

    public function decryptByPassword($data, $password = '')
    {
        $password = $password ?: \Yii::$app->params['cipherPassword'];
        return parent::decryptByPassword($data, $password); // TODO: Change the autogenerated stub
    }

}